# COMMERCE

# 0. INTRODUCTION

# 1. MODELS
Fist, I defined a string name to User and I went to python3 manage.py shell to add data and see some output - it was nice to see those things working.
And "AbstractUser" is a predefined class that exists in django.contrib.auth.models that is VERY useful.
When I tried to compile with a class with a ForeignKey before define the class witch this key as Primary I got an error of "not defined". 
Quando cria o password pelo py, ele fica com os caracteres originais registrados - IMPORTANTE.
Remember, that with $ sqlite filename.sql is possible to run queryes on terminal. 
Dealing with data in python shell, the id doesn't show up until I saved the data in db. 
With these observations, looks like the django-db relation is working fine. 
